language: go
go:
- release
install:
- go get -d -t -v ./...
- go get -v code.google.com/p/go.tools/cmd/vet
- go get -v code.google.com/p/go.tools/cmd/cover
- go get -v github.com/davecgh/go-spew/spew
script:
- export PATH=$PATH:$HOME/gopath/bin
- go vet ./...
- go test -v -covermode=count -coverprofile=profile.cov
after_success:
- go get -v github.com/mattn/goveralls
- goveralls -coverprofile=profile.cov -service=travis-ci
